version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 55072:1972
      - 55038:52773
      - 53773
      - 55030:5000
    volumes:
      - ./:/home/irisowner/dev
    command: ["-a", "/home/irisowner/dev/iris_post_start_script.sh"]
  ollama:
    image: ollama/ollama:latest
    environment:
      - MODEL=mistral
      - EMBEDDINGMODEL=mxbai-embed-large
    volumes:
      - ./ollama/:/root/.ollama
    ports:
      - 11434:11434
    entrypoint: ["sh", "/root/.ollama/entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
